version: '3.1'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=user_todo
      - POSTGRES_PASSWORD=1122
    ports:
      - 5432:5432

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - 54321:80
    depends_on:
      - postgres