version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=user_todo
      - POSTGRES_PASSWORD=1122
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080